- id: '1778526312883'
  alias: Run PND
  description: ''
  triggers:
  - at: 06:00:00
    trigger: time
  conditions: []
  actions:
  - event: run_pnd
    event_data: {}
  mode: single
- id: '1778526595548'
  alias: Run actions after AppDaemon starts
  description: Spustí PND po startu AppDaemonu s prodlevou 15 sekund pro zajištění
    závislostí
  triggers:
  - event_type: APPDAEMON_READY
    trigger: event
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - event: run_pnd
    event_data: {}
  mode: single
