### HISTORY sensors
- platform: history_stats
  type: time
  name: Filtrace spuštěna
  unique_id: filtrace_spustena_daily_hours
  entity_id: binary_sensor.pool_pump_running
  state: "on"
  start: "{{ today_at() }}"
  end: "{{ now() }}"
- platform: statistics
  unique_id: sensor.base_avg_daily_consumption
  name: "Base Average Daily Consumption"
  entity_id: sensor.base_final_daily_house_consumption
  state_characteristic: mean
  sampling_size: 7
  max_age:
    days: 7
